export const gluonTypesData = { 
1 :{ type: 'NATIONALITY', caption: 'is from', caption_ja: '国籍'},
2 :{ type: 'CHILD_OF', caption: 'is a child of', caption_ja: 'の子供'},
3 :{ type: 'SON_OF', caption: 'is a son of', caption_ja: 'の息子'},
4 :{ type: 'DAUGHTER_OF', caption: 'is a daughter of', caption_ja: 'の娘'},
5 :{ type: 'SIBLING_OF', caption: 'is a sibling of', caption_ja: 'の兄弟（姉妹）'},
6 :{ type: 'TWINS_OF', caption: 'is a twin of', caption_ja: 'と双子'},
7 :{ type: 'BROTHER_OF', caption: 'is a brother of', caption_ja: 'の兄弟'},
8 :{ type: 'SISTER_OF', caption: 'is a sister of', caption_ja: 'の姉妹'},
9 :{ type: 'GRANDCHILD_OF', caption: 'is a grandchild of', caption_ja: 'の孫'},
10 :{ type: 'GREAT_GRANDCHILD_OF', caption: 'is a great grandchild of', caption_ja: 'のひ孫'},
11 :{ type: 'COUSIN_OF', caption: 'is a cousin of', caption_ja: 'のいとこ'},
12 :{ type: 'DESCENDANT_OF', caption: 'is a descendant of', caption_ja: 'の子孫'},
13 :{ type: 'ADOPTED_CHILD_OF', caption: 'is an adopted child of', caption_ja: 'の養子'},
14 :{ type: 'RELATIVE_OF', caption: 'is a relative of', caption_ja: 'と血縁関係にある'},
15 :{ type: 'WIFE_OF', caption: 'is a wife of', caption_ja: 'の妻'},
16 :{ type: 'CONCUBINE_OF', caption: 'is a concubine of', caption_ja: 'の妾'},
17 :{ type: 'DATING_WITH', caption: 'is dating with', caption_ja: 'の恋人'},
18 :{ type: 'IMMORAL_RELATION_WITH', caption: 'is in immoral relation with', caption_ja: 'と不倫関係'},
19 :{ type: 'IN_LAW_FAMILY_OF', caption: 'is in law family of', caption_ja: 'と養子縁組家族'},
20 :{ type: 'FRIEND_OF', caption: 'is a friend of', caption_ja: 'の友人'},
21 :{ type: 'APPRENTICE_OF', caption: 'is an apprentice of', caption_ja: 'の弟子'},
22 :{ type: 'KNOWS', caption: 'knows', caption_ja: 'の知人'},
23 :{ type: 'GRADUATE_OF', caption: 'was graduated from', caption_ja: 'を卒業した'},
24 :{ type: 'MASTER_DEGREE_OF', caption: 'has a master degree of', caption_ja: '院を卒業した'},
25 :{ type: 'STUDIED_AT', caption: 'studied at', caption_ja: 'に就学する'},
26 :{ type: 'MEMBER_OF', caption: 'is a member of', caption_ja: 'のメンバー'},
27 :{ type: 'AFFILIATION', caption: 'is affiliated to', caption_ja: 'に所属'},
28 :{ type: 'WORKS_FOR', caption: 'works for', caption_ja: 'に勤務'},
29 :{ type: 'COLLEAGUE', caption: 'is a colleague of', caption_ja: 'の同僚'},
30 :{ type: 'VOCAL_OF', caption: 'is a vocal of', caption_ja: 'のボーカリスト'},
31 :{ type: 'GUITARIST_OF', caption: 'is a guitarist of', caption_ja: 'のギタリスト'},
32 :{ type: 'BASSIST_OF', caption: 'is a bassist of', caption_ja: 'のベーシスト'},
33 :{ type: 'KEYBOARDIST_OF', caption: 'is a keyboardist of', caption_ja: 'のキーボーディスト'},
34 :{ type: 'DRUMMER_OF', caption: 'is a drummer of', caption_ja: 'のドラマー'},
35 :{ type: 'DANCER_OF', caption: 'is a dancer of', caption_ja: 'のダンサー'},
36 :{ type: 'FOUNDER_OF', caption: 'is a founder of', caption_ja: 'の創業者'},
37 :{ type: 'CEO_OF', caption: 'is ceo of', caption_ja: 'のCEO'},
38 :{ type: 'BOARD_MEMBER_OF', caption: 'is a boardMember of', caption_ja: 'の役員'},
39 :{ type: 'MINISTER_OF', caption: 'is minister of', caption_ja: 'の大臣'},
40 :{ type: 'HEAD_OF', caption: 'is the head of', caption_ja: 'の責任者'},
41 :{ type: 'COACH_OF', caption: 'is a coach of', caption_ja: 'のコーチ'},
42 :{ type: 'FUNDER_OF', caption: 'is funder of', caption_ja: 'に出資'},
43 :{ type: 'PARENT_ORGANIZATION_OF', caption: 'is parent organization of', caption_ja: 'の親会社'},
44 :{ type: 'SUB_ORGANIZATION_OF', caption: 'is sub organization of', caption_ja: '傘下の組織'},
45 :{ type: 'SUB_FAMILY_OF', caption: 'is sub family of', caption_ja: 'の支流家族'},
46 :{ type: 'OWNS', caption: 'owns', caption_ja: 'を所有'},
47 :{ type: 'RUNS', caption: 'runs', caption_ja: 'を運営する'},
48 :{ type: 'ESTABLISHED', caption: 'established', caption_ja: 'を設立した'},
49 :{ type: 'ACQUISITION', caption: 'made acquisition with', caption_ja: 'を買収'},
50 :{ type: 'ACQUIRED_BY', caption: 'was acquired by', caption_ja: 'に買収された'},
51 :{ type: 'DEPARTMENT_OF', caption: 'is a department of', caption_ja: 'の内部無局'},
52 :{ type: 'BRAND_BY', caption: 'is a brand by', caption_ja: 'のブランド'},
53 :{ type: 'LOCATED_AT', caption: 'is located at', caption_ja: 'に所在'},
54 :{ type: 'CREATOR_OF', caption: 'is the creator of', caption_ja: 'の作者'},
55 :{ type: 'AUTHOR_OF', caption: 'is the author of', caption_ja: 'の著者'},
56 :{ type: 'ARTIST_OF', caption: 'is the artist of', caption_ja: 'の制作者'},
57 :{ type: 'PRODUCER_OF', caption: 'is the producer of', caption_ja: 'のプロデューサー'},
58 :{ type: 'DIRECTOR_OF', caption: 'is a director of', caption_ja: 'のディレクター'},
59 :{ type: 'PUBLISHER_OF', caption: 'is the publisher of', caption_ja: 'の出版社'},
60 :{ type: 'PRODUCTION_COMPANY_OF', caption: 'is the production company of', caption_ja: 'のプロダクション会社'},
61 :{ type: 'CONTRIBUTOR_OF', caption: 'is a contributor of', caption_ja: 'の貢献者'},
62 :{ type: 'ACTOR_OF', caption: 'is an actor of', caption_ja: 'に出演'},
63 :{ type: 'PERFORMED', caption: 'performed in', caption_ja: 'に出演'},
64 :{ type: 'PLAYS_AT', caption: 'plays at', caption_ja: 'に所属'},
65 :{ type: 'CHARACTER_OF', caption: 'is a character of', caption_ja: 'のキャラクター'},
66 :{ type: 'IS_BASED_ON', caption: 'is based on', caption_ja: 'を原作とする'},
67 :{ type: 'TRACK', caption: 'is a track in', caption_ja: 'のトラック'},
68 :{ type: 'MANUFACTURER_OF', caption: 'is a manufacturer of', caption_ja: 'の開発者'},
69 :{ type: 'MANUFACTURED_BY', caption: 'is manufactured by', caption_ja: 'により開発された'},
70 :{ type: 'ORGANIZER_OF', caption: 'is an organizer of', caption_ja: 'を主宰'},
71 :{ type: 'ATTENDEE_OF', caption: 'is an attendee of', caption_ja: 'に出席'},
72 :{ type: 'IS_ELECTED', caption: 'is elected', caption_ja: 'に当選'},
73 :{ type: 'PARTICIPATED', caption: 'participated', caption_ja: 'に参画'},
74 :{ type: 'EXECUTED', caption: 'executed', caption_ja: 'を実施'},
75 :{ type: 'ACHIEVED', caption: 'achieved', caption_ja: 'を達成'},
76 :{ type: 'IS_AS', caption: 'is', caption_ja: 'である'},
77 :{ type: 'IS_ONE_OF', caption: 'is one of', caption_ja: 'のひとつ'},
78 :{ type: 'IS_FROM', caption: 'is from', caption_ja: 'の出身'},
79 :{ type: 'WORKS_AS', caption: 'works as', caption_ja: 'として活動'},
}
